// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByfRmTPTbp_DDQPcCTdzA75CJJ6BfhjtY',
    appId: '1:455229886914:web:26898bebf7c82a86b7065b',
    messagingSenderId: '455229886914',
    projectId: 'dma-mobile',
    authDomain: 'dma-mobile.firebaseapp.com',
    storageBucket: 'dma-mobile.appspot.com',
    measurementId: 'G-RQXRGKPZPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0spS-dZbydAmfa4rsbEyg2clEEWNviI',
    appId: '1:455229886914:android:ba9d61b00ac37825b7065b',
    messagingSenderId: '455229886914',
    projectId: 'dma-mobile',
    storageBucket: 'dma-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JXnoGpoBW-dYj5Gk6MBftizhY3HKyFA',
    appId: '1:455229886914:ios:fef02a1c245af477b7065b',
    messagingSenderId: '455229886914',
    projectId: 'dma-mobile',
    storageBucket: 'dma-mobile.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1JXnoGpoBW-dYj5Gk6MBftizhY3HKyFA',
    appId: '1:455229886914:ios:7a1d857d340736d5b7065b',
    messagingSenderId: '455229886914',
    projectId: 'dma-mobile',
    storageBucket: 'dma-mobile.appspot.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
